---
- name: example copying file with owner and permissions
  copy:
    src: "{{ role_path }}/files/properties.example.conf"
    dest: "{{ install_dir }}/properties.example.conf"
    owner: ec2-user
    group: ec2-user
    mode: 0644